const TRACKED_WALLETS = [
    {
        address: "7ABz8qEFZTHPkovMDsmQkm64DZWN5wRtU7LEtD2ShkQ6",
        name: "Red",
        description: "Solana Trader",
        twitter: "https://x.com/redwithbag",
        telegram: "https://t.me/yvlred",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    {
        address: "4wwHh4fzdVTZjmhGHfQUBFasJ3TdQJHNmkfMBwzXEmYL",
        name: "Geni",
        description: "Solana Trader",
        twitter: "https://x.com/Geni100x",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "525LueqAyZJueCoiisfWy6nyh4MTvmF4X9jSqi6efXJT",
        name: "Joji",
        description: "Solana Trader",
        twitter: "https://x.com/metaversejoji",
        telegram: "https://t.me/jojiinnercircle",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4F2AHuw55m9ojKpFfsofmhAwB979ECVRFVurEam4phqU",
        name: "Lunix",
        description: "Solana Trader",
        twitter: "https://x.com/SolLunix",
        telegram: "https://t.me/lunixgambles",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HtucFepgUkMpHdrYsxMqjBNN6qVBdjmFaLZneNXopuJm",
        name: "Frostyjays",
        description: "Solana Trader",
        twitter: "https://x.com/FrostyJayss",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "8MaVa9kdt3NW4Q5HyNAm1X5LbR8PQRVDc1W8NMVK88D5",
        name: "Daumen",
        description: "Solana Trader",
        twitter: "https://x.com/daumeneth",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "ApRnQN2HkbCn7W2WWiT2FEKvuKJp9LugRyAE1a9Hdz1",
        name: "S",
        description: "Solana Trader",
        twitter: "https://x.com/runitbackghost",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR",
        name: "Casino",
        description: "Solana Trader",
        twitter: "https://x.com/casino616",
        telegram: "https://t.me/casino_calls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "41uh7g1DxYaYXdtjBiYCHcgBniV9Wx57b7HU7RXmx1Gg",
        name: "Lowskii",
        description: "Solana Trader",
        twitter: "https://x.com/Lowskii_gg",
        telegram: "https://t.me/lowskiistradejournal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "6LChaYRYtEYjLEHhzo4HdEmgNwu2aia8CM8VhR9wn6n7",
        name: "Assasin.eth",
        description: "Solana Trader",
        twitter: "https://x.com/assasin_eth",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "6m5sW6EAPAHncxnzapi1ZVJNRb9RZHQ3Bj7FD84X9rAF",
        name: "ShockedJS",
        description: "Solana Trader",
        twitter: "https://x.com/ShockedJS",
        telegram: "https://t.me/shockedjstrading",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5B52w1ZW9tuwUduueP5J7HXz5AcGfruGoX6YoAudvyxG",
        name: "Yenni",
        description: "Solana Trader",
        twitter: "https://x.com/Yennii56",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9Vk7pkBZ9KFJmzaPzNYjGedyz8qoKMQtnYyYi2AehNMT",
        name: "Xelf",
        description: "Solana Trader",
        twitter: "https://x.com/xelf_sol",
        telegram: "https://t.me/xelfalpha",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "Gv7CnRo2L2SJ583XEfoKHKbmWK3wNoBDxVoJqMKJR4Nu",
        name: "Robo",
        description: "Solana Trader",
        twitter: "https://x.com/roboPBOC",
        telegram: "https://t.me/robogems",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "D2wBctC1K2mEtA17i8ZfdEubkiksiAH2j8F7ri3ec71V",
        name: "Dior",
        description: "Solana Trader",
        twitter: "https://x.com/Dior100x",
        telegram: "https://t.me/Diorscabal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9vWutdTBs66hWkeCmxaLFpkKy4q5RSe8DsFjfdxj5yFA",
        name: "Dutch",
        description: "Solana Trader",
        twitter: "https://x.com/0xDutch_",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4AHgEkTsGqY77qtde4UJn9yZCrbGcM7UM3vjT3qM4G5H",
        name: "BagCalls",
        description: "Solana Trader",
        twitter: "https://x.com/BagCalls",
        telegram: "https://t.me/bagcalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "EAnB5151L8ejp3SM6haLgyv3snk6oqc8acKgWEg9T5J",
        name: "Jordan",
        description: "Solana Trader",
        twitter: "https://x.com/ohFrostyyy",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "EaVboaPxFCYanjoNWdkxTbPvt57nhXGu5i6m9m6ZS2kK",
        name: "Danny",
        description: "Solana Trader",
        twitter: "https://x.com/cladzsol",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9AqzsYXj1M2z8shG6resmM7LNM6GdvsjcjhjRUPc1dNf",
        name: "Cuh",
        description: "Solana Trader",
        twitter: "https://x.com/quarsays",
        telegram: "https://t.me/cuhcooks",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HmBmSYwYEgEZuBUYuDs9xofyqBAkw4ywugB1d7R7sTGh",
        name: "Tobx",
        description: "Solana Trader",
        twitter: "https://x.com/TobxG",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "Ds8mcuP5r2phg596mLui3ti3PJtVvFRw19Eo9UFdJ5Bc",
        name: "Jazz",
        description: "Solana Trader",
        twitter: "https://x.com/youngjazzeth",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "Ebk5ATdfrCuKi27dHZaw5YYsfREEzvvU8xeBhMxQoex6",
        name: "Sully",
        description: "Solana Trader",
        twitter: "https://x.com/sullyfromDeets",
        telegram: "https://t.me/kitchenofsully",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "FEYmfSL4B3Hhk5BzyEJNpHRiwAoMvzdNe2oa1UTKmbYT",
        name: "idontpaytaxes",
        description: "Solana Trader",
        twitter: "https://x.com/untaxxable",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9FNz4MjPUmnJqTf6yEDbL1D4SsHVh7uA8zRHhR5K138r",
        name: "Danny",
        description: "Solana Trader",
        twitter: "https://x.com/0xSevere",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "ATKi3ZvMbo31pbgBgGSGQPDPKEbQ4oGzoDrwG2sms56k",
        name: "Nach",
        description: "Solana Trader",
        twitter: "https://x.com/NachSOL",
        telegram: "https://t.me/NarrativeNach",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7SvvTJSwcpNQCDGEt14zuoPFoSsaveGd7UWgiJGQLAHN",
        name: "Mero",
        description: "Solana Trader",
        twitter: "https://x.com/MeroFN",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4jFPYSoUTRaFbFDJp9QpA1J5pXJmMJYoWhiFTpoLPq6X",
        name: "Merk",
        description: "Solana Trader",
        twitter: "https://x.com/MerkTrading",
        telegram: "https://t.me/MerkTradingCalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HUS9ErdrDqpqQePbmfgJUTnDTE6eZ8ES62a25RihSK9U",
        name: "Hustler",
        description: "Solana Trader",
        twitter: "https://x.com/JoeVargas",
        telegram: "https://t.me/hustlersalpha",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5wcc13mXoyqe6qh2iHH5GFknojoJ7y13ZPx9K4NXTuo3",
        name: "Dolo",
        description: "Solana Trader",
        twitter: "https://x.com/doloxbt",
        telegram: "https://t.me/DolosTradingDojo",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "3FDci33mzMKNdNxzSS9D13XyNZQAdfmpvtDZLWPbZiAU",
        name: "Sachs",
        description: "Solana Trader",
        twitter: "https://x.com/gudmansachs",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5AyJw1VNDgTho2chipbVmuGqTuX1fCvVkLneChQkQrw8",
        name: "Bolivian",
        description: "Solana Trader",
        twitter: "https://x.com/_bolivian",
        telegram: "https://t.me/boliviantrades",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "42nsEk51owYM3uciuRvFerqK77yhXZyjBLRgkDzJPV2g",
        name: "Izzy",
        description: "Solana Trader",
        twitter: "https://x.com/degenIzzy",
        telegram: "https://t.me/izzyDegens",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "AGnd5WTHMUbyK3kjjQPdQFM3TbWcuPTtkwBFWVUwiCLu",
        name: "Angi",
        description: "Solana Trader",
        twitter: "https://x.com/angitradez",
        telegram: "https://t.me/angiscalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "3mPypxb7ViYEdLv4siFmESvY5w5ZKknwgmB4TPcZ77qe",
        name: "Carti The Menace",
        description: "Solana Trader",
        twitter: "https://x.com/CartiTheMenace",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "C4BWYccLsbeHgZzVupFZJGvJK2nQpn8em9WtzURH4gZW",
        name: "Obijai",
        description: "Solana Trader",
        twitter: "https://x.com/Obijai",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HrCPnDvDgbpbFxKxer6Pw3qEcfAQQNNjb6aJNFWgTEng",
        name: "0xWinged",
        description: "Solana Trader",
        twitter: "https://x.com/0xExorcized",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9yGxZ43ngT7LvwquVdUAYPvJzVyY65cS6mQvuJXjTEUc",
        name: "Xet",
        description: "Solana Trader",
        twitter: "https://x.com/xet",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM",
        name: "Dex",
        description: "Solana Trader",
        twitter: "https://x.com/igndex",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC",
        name: "Nyhrox",
        description: "Solana Trader",
        twitter: "https://x.com/nyhrox",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "c3XGUoDSBaJDA8qaJ5pUkCnamMERwZLJBVjxdkNepGo",
        name: "Moggi",
        description: "Solana Trader",
        twitter: "https://x.com/10piecedawg",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "F72vY99ihQsYwqEDCfz7igKXA5me6vN2zqVsVUTpw6qL",
        name: "Jalen",
        description: "Solana Trader",
        twitter: "https://x.com/RipJalens",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "AE3tJDEyUdwBM8ZoUb3iCo563gMbq26JtckfvjcVZbSa",
        name: "Roxo",
        description: "Solana Trader",
        twitter: "https://x.com/RoxoXBT",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "D6JrzpAKtLT4XQmgVKxdKZwFxJ4HmZWVKmMfKEK4av6d",
        name: "Solana Plays",
        description: "Solana Trader",
        twitter: "https://x.com/SolanaPlays",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4Be9CvxqHW6BYiRAxW9Q3xu1ycTMWaL5z8NX4HR3ha7t",
        name: "Mitch",
        description: "Solana Trader",
        twitter: "https://x.com/1solinfeb",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7SDs3PjT2mswKQ7Zo4FTucn9gJdtuW4jaacPA65BseHS",
        name: "Insentos",
        description: "Solana Trader",
        twitter: "https://x.com/insentos",
        telegram: "https://t.me/insentos",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5rkPDK4JnVAumgzeV2Zu8vjggMTtHdDtrsd5o9dhGZHD",
        name: "Dave Portnoy",
        description: "Solana Trader",
        twitter: "https://x.com/stoolpresidente",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "FbvUU5qvD9JsU9jp3KDweCpZiVZHLoQBQ1PPCAAbd6FB",
        name: "Profitier",
        description: "Solana Trader",
        twitter: "https://x.com/profitierr",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "2BU3NAzgRA2gg2MpzwwXpA8X4CCRaLgrf6TY1FKfJPX2",
        name: "Issa",
        description: "Solana Trader",
        twitter: "https://x.com/issathecooker",
        telegram: "https://t.me/issasthoughts",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "ExKCuoAzJCgCVjU3CvNoL8vVrdESTWkx3ubj6rQXwQM4",
        name: "TheDefiApe",
        description: "Solana Trader",
        twitter: "https://x.com/TheDefiApe",
        telegram: "https://t.me/DEFIAPEALERTS",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "EdDCRfDDeiiDXdntrP59abH4DXHFNU48zpMPYisDMjA7",
        name: "Mezoteric",
        description: "Solana Trader",
        twitter: "https://x.com/mezoteric",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "AbcX4XBm7DJ3i9p29i6sU8WLmiW4FWY5tiwB9D6UBbcE",
        name: "404Flipped",
        description: "Solana Trader",
        twitter: "https://x.com/404flipped",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HLv6yCEpgjQV9PcKsvJpem8ESyULTyh9HjHn9CtqSek1",
        name: "Lyxe",
        description: "Solana Trader",
        twitter: "https://x.com/cryptolyxe",
        telegram: "https://t.me/+yFy-8j3uwBBjMzhl",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4EsY8HQB4Ak65diFrSHjwWhKSGC8sKmnzyusM993gk2w",
        name: "Prosciutto",
        description: "Solana Trader",
        twitter: "https://x.com/prosciuttosol",
        telegram: "https://t.me/prosciuttosol",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm",
        name: "Ansem",
        description: "Solana Trader",
        twitter: "https://x.com/blknoiz06",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DBmRHNbSsVX8F6NyVaaaiuGdwo1aYGawiy3jfNcvXYSC",
        name: "Bobby",
        description: "Solana Trader",
        twitter: "https://x.com/retardmode",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7i7vHEv87bs135DuoJVKe9c7abentawA5ydfWcWc8iY2",
        name: "ChartFu",
        description: "Solana Trader",
        twitter: "https://x.com/ChartFuMonkey",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4S9U8HckRngscHWrW418cG6Suw62dhEZzmyrT2hxSye5",
        name: "Polar",
        description: "Solana Trader",
        twitter: "https://x.com/polarsterrr",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "B3beyovNKBo4wF1uFrfGfpVeyEHjFyJPmEBciz7kpnoS",
        name: "CC2",
        description: "Solana Trader",
        twitter: "https://x.com/CC2Ventures",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "CRVidEDtEUTYZisCxBZkpELzhQc9eauMLR3FWg74tReL",
        name: "Frank",
        description: "Solana Trader",
        twitter: "https://x.com/frankdegods",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV",
        name: "Bastille",
        description: "Solana Trader",
        twitter: "https://x.com/BastilleBtc",
        telegram: "https://t.me/+L3m70UCPyzJmYTY1",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "B7FDzJnb7DLYH1A37tKEFss1RRSz5C7MYgTRRMaWzBqa",
        name: "Lucas",
        description: "Solana Trader",
        twitter: "https://x.com/LockedInLucas",
        telegram: "https://t.me/frontruncalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DeVjHYTEZEi7Wvcvfjz8KZMzpuZpijABgutSfXn1BxjX",
        name: "Duke",
        description: "Solana Trader",
        twitter: "https://x.com/dukezfn",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "GwoFJFjUTUSWq2EwTz4P2Sznoq9XYLrf8t4q5kbTgZ1R",
        name: "Levis",
        description: "Solana Trader",
        twitter: "https://x.com/LevisNFT",
        telegram: "https://t.me/LevisAlpha",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "iWinRYGEWcaFFqWfgjh28jnqWL72XUMmUfhADpTQaRL",
        name: "Scooter",
        description: "Solana Trader",
        twitter: "https://x.com/imperooterxbt",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "F5TjPySiUJMdvqMZHnPP85Rc1vErDGV5FR5P2vdVm429",
        name: "Zyaf",
        description: "Solana Trader",
        twitter: "https://x.com/0xZyaf",
        telegram: "https://t.me/zyafgambles",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HwRnKq7RPtKHvX9wyHsc1zvfHtGjPQa5tyZtGtbvfXE",
        name: "Jay",
        description: "Solana Trader",
        twitter: "https://x.com/BitBoyJay",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7VBTpiiEjkwRbRGHJFUz6o5fWuhPFtAmy8JGhNqwHNnn",
        name: "Brox",
        description: "Solana Trader",
        twitter: "https://x.com/ohbrox",
        telegram: "https://t.me/broxcalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4vw54BmAogeRV3vPKWyFet5yf8DTLcREzdSzx4rw9Ud9",
        name: "Decu",
        description: "Solana Trader",
        twitter: "https://x.com/Decu0x",
        telegram: "https://t.me/DecusCalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "HCQb4Qrtk4qCfChDH8XvM5onymmCSmRj9bddV6QCPdRe",
        name: "Rektober",
        description: "Solana Trader",
        twitter: "https://x.com/rektober",
        telegram: "https://t.me/RektNFA",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "CSHktdVEmJybwNR9ft3sDfSc2UKgTPZZ8km26XfHYZDt",
        name: "Lynk",
        description: "Solana Trader",
        twitter: "https://x.com/lynk0x",
        telegram: "https://t.me/lynkscabal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4WPTQA7BB4iRdrPhgNpJihGcxKh8T43gLjMn5PbEVfQw",
        name: "Oura",
        description: "Solana Trader",
        twitter: "https://x.com/Oura456",
        telegram: "https://t.me/OuraEmergencyCalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "6Qs6joB349h7zu1z9xRgPgMSmpBYLDQb2wtAecY4LysH",
        name: "Chefin",
        description: "Solana Trader",
        twitter: "https://x.com/Chefin100x",
        telegram: "https://t.me/ChefinAlpha",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "Aen6LKc7sGVPTyjMd5cu9B9XVjL7m9pnvAiP2ZNJC4GZ",
        name: "Aroa",
        description: "Solana Trader",
        twitter: "https://x.com/AroaOnSol",
        telegram: "https://t.me/AroasJournal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "3nvC8cSrEBqFEXZjUpKfwZMPk7xYdqcnoxmFBjXiizVX",
        name: "Value & Time",
        description: "Solana Trader",
        twitter: "https://x.com/valueandtime",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN",
        name: "Beaver",
        description: "Solana Trader",
        twitter: "https://x.com/beaverd",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7N4bAyZX6z39RozQh7GC8VQmgjvjkkWmSyAt1wdMjEmq",
        name: "Zinc",
        description: "Solana Trader",
        twitter: "https://x.com/Zinc_ETH",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "H9h6UV9cwWWogcTZ5gbzQ6Z3dYDNaiJ3mUWw3aGnE3Mc",
        name: "Monarky",
        description: "Solana Trader",
        twitter: "https://x.com/MonarkyMemes",
        telegram: "https://t.me/MonarkyCalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "2kv8X2a9bxnBM8NKLc6BBTX2z13GFNRL4oRotMUJRva9",
        name: "Gh0stee",
        description: "Solana Trader",
        twitter: "https://x.com/4GH0STEE",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DsqRyTUh1R37asYcVf1KdX4CNnz5DKEFmnXvgT4NfTPE",
        name: "Classic",
        description: "Solana Trader",
        twitter: "https://x.com/mrclassic33",
        telegram: "https://t.me/mrclassiccalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DpNVrtA3ERfKzX4F8Pi2CVykdJJjoNxyY5QgoytAwD26",
        name: "Gorilla Capital",
        description: "Solana Trader",
        twitter: "https://x.com/gorillacapsol",
        telegram: "https://t.me/gorillacapitalcooks",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "831qmkeGhfL8YpcXuhrug6nHj1YdK3aXMDQUCo85Auh1",
        name: "Meechie",
        description: "Solana Trader",
        twitter: "https://x.com/973Meech",
        telegram: "https://t.me/NotACallerChannel",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9K18MstUaXmSFSBoa9qDTqWTnYhTZqdgEhuKRTVRgh6g",
        name: "Sabby",
        description: "Solana Trader",
        twitter: "https://x.com/sabby_eth",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4DdrfiDHpmx55i4SPssxVzS9ZaKLb8qr45NKY9Er9nNh",
        name: "Mr Frog",
        description: "Solana Trader",
        twitter: "https://x.com/TheMisterFrog",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7tiRXPM4wwBMRMYzmywRAE6jveS3gDbNyxgRrEoU6RLA",
        name: "QtDegen",
        description: "Solana Trader",
        twitter: "https://x.com/qtdegen",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "3h65MmPZksoKKyEpEjnWU2Yk2iYT5oZDNitGy5cTaxoE",
        name: "Jidn",
        description: "Solana Trader",
        twitter: "https://x.com/jidn_w",
        telegram: "https://t.me/JidnLosesMoney",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "34ZEH778zL8ctkLwxxERLX5ZnUu6MuFyX9CWrs8kucMw",
        name: "Groovy",
        description: "Solana Trader",
        twitter: "https://x.com/0xGroovy",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "CqQKv6XdrMWrz3YuSwqTTcVoQK5eu4zNo3hps3M1Q3yo",
        name: "Jaden",
        description: "Solana Trader",
        twitter: "https://x.com/JadenOnChain",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5x8tfrJSn4Pt5gjQEMWDnoLvAzZ8rgJVTXiTpcwhbxmN",
        name: "Tahi",
        description: "Solana Trader",
        twitter: "https://x.com/Tahifn",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "8YYDiCbPd4nM8TxrQEVdPA4aG8jys8R7Z1kKsgPL4pwh",
        name: "Michi",
        description: "Solana Trader",
        twitter: "https://x.com/michigems",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm",
        name: "Gake",
        description: "Solana Trader",
        twitter: "https://x.com/Ga__ke",
        telegram: "https://t.me/GakesBakes",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "FRbUNvGxYNC1eFngpn7AD3f14aKKTJVC6zSMtvj2dyCS",
        name: "Henn100x",
        description: "Solana Trader",
        twitter: "https://x.com/henn100x",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "831yhv67QpKqLBJjbmw2xoDUeeFHGUx8RnuRj9imeoEs",
        name: "Trey",
        description: "Solana Trader",
        twitter: "https://x.com/treysocial",
        telegram: "https://t.me/treystele",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "m7Kaas3Kd8FHLnCioSjCoSuVDReZ6FDNBVM6HTNYuF7",
        name: "Ferb",
        description: "Solana Trader",
        twitter: "https://x.com/ferbsol",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "2CXbN6nuTTb4vCrtYM89SfQHMMKGPAW4mvFe6Ht4Yo6z",
        name: "MoneyMaykah",
        description: "Solana Trader",
        twitter: "https://x.com/moneymaykah_",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "E33jP6RWVpGkv3fDVbuR5Ee6ak42tTKW9yYszqERtobs",
        name: "Jerry",
        description: "Solana Trader",
        twitter: "https://x.com/chefjerrry",
        telegram: "https://t.me/jerrycabal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "2YJbcB9G8wePrpVBcT31o8JEed6L3abgyCjt5qkJMymV",
        name: "Al4n",
        description: "Solana Trader",
        twitter: "https://x.com/Al4neu",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "5TuiERc4X7EgZTxNmj8PHgzUAfNHZRLYHKp4DuiWevXv",
        name: "Rev",
        description: "Solana Trader",
        twitter: "https://x.com/solrevv",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt",
        name: "The Doc",
        description: "Solana Trader",
        twitter: "https://x.com/KayTheDoc",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "BCnqsPEtA1TkgednYEebRpkmwFRJDCjMQcKZMMtEdArc",
        name: "Kreo",
        description: "Solana Trader",
        twitter: "https://x.com/kreo444",
        telegram: "https://t.me/kreocalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "AJ6MGExeK7FXmeKkKPmALjcdXVStXYokYNv9uVfDRtvo",
        name: "Tim",
        description: "Solana Trader",
        twitter: "https://x.com/timmpix1",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6",
        name: "Cooker",
        description: "Solana Trader",
        twitter: "https://x.com/CookerFlips",
        telegram: "https://t.me/CookersCooks",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "J2B5fnm2DAAUAGa4EaegwQFoYaN6B5FerGA5sjtQoaGM",
        name: "Dan176",
        description: "Solana Trader",
        twitter: "https://x.com/176Dan",
        telegram: "https://t.me/DansCall",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "7iabBMwmSvS4CFPcjW2XYZY53bUCHzXjCFEFhxeYP4CY",
        name: "Leens",
        description: "Solana Trader",
        twitter: "https://x.com/leensx100",
        telegram: "https://t.me/leenscooks",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "F2SuErm4MviWJ2HzKXk2nuzBC6xe883CFWUDCPz6cyWm",
        name: "Earl",
        description: "Solana Trader",
        twitter: "https://x.com/earlTrades",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk",
        name: "Jijo",
        description: "Solana Trader",
        twitter: "https://x.com/jijo_exe",
        telegram: "https://t.me/jijosjournal",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "BXNiM7pqt9Ld3b2Hc8iT3mA5bSwoe9CRrtkSUs15SLWN",
        name: "Absol",
        description: "Solana Trader",
        twitter: "https://x.com/absolquant",
        telegram: "https://t.me/absolcalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "96sErVjEN7LNJ6Uvj63bdRWZxNuBngj56fnT9biHLKBf",
        name: "Orange",
        description: "Solana Trader",
        twitter: "https://x.com/OrangeSBS",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "73LnJ7G9ffBDjEBGgJDdgvLUhD5APLonKrNiHsKDCw5B",
        name: "Waddles",
        description: "Solana Trader",
        twitter: "https://x.com/traderpow",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "8zFZHuSRuDpuAR7J6FzwyF3vKNx4CVW3DFHJerQhc7Zd",
        name: "Pow",
        description: "Solana Trader",
        twitter: "https://x.com/traderpow",
        telegram: "https://t.me/PowsGemCalls",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD",
        name: "Publix",
        description: "Solana Trader",
        twitter: "https://x.com/publixplays",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd",
        name: "dv",
        description: "Solana Trader",
        twitter: "https://x.com/vibed333",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "EHg5YkU2SZBTvuT87rUsvxArGp3HLeye1fXaSDfuMyaf",
        name: "TIL",
        description: "Solana Trader",
        twitter: "https://x.com/tilcrypto",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj",
        name: "Euris",
        description: "Solana Trader",
        twitter: "https://x.com/Euris_JT",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN",
        name: "West",
        description: "Solana Trader",
        twitter: "https://x.com/ratwizardx",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65",
        name: "Latuche",
        description: "Solana Trader",
        twitter: "https://x.com/Latuche95",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP",
        name: "OGantD",
        description: "Solana Trader",
        twitter: "https://x.com/0GAntD",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o",
        name: "Cented",
        description: "Solana Trader",
        twitter: "https://x.com/Cented7",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "BTf4A2exGK9BCVDNzy65b9dUzXgMqB4weVkvTMFQsadd",
        name: "Kev",
        description: "Solana Trader",
        twitter: "https://x.com/Kevsznx",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    },
    { 
        address: "9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL",
        name: "Loopier",
        description: "Solana Trader",
        twitter: "https://x.com/Loopierr",
        telegram: "https://t.me/loopierrsjourney",
        avatar: "https://unavatar.io/twitter/SolLunix",
        tags: ["DeFi"],
        trades: [],
        activities: [],
        historicalPnL: []
    }
]

module.exports = { TRACKED_WALLETS };